spring:
  application:
    name: NotifyTrafficTelegramBot

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

notify:
  service:
    url: ${NOTIFICATION_SERVICE_URL}

server:
  address: 0.0.0.0
  port: 8080
