spring:
  application:
    name: NotifyTrafficIntegration

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:/db/changelog/v1.0.0/db.changelog-master.xml

server:
  port: 8080

google:
  maps:
    token: AIzaSyD7EiwFgtZ3WCcPi6uGRRiVeDqLJQtaejw
    distance-matrix-url: https://maps.googleapis.com/maps/api/distancematrix/json?origins={origins}&mode=driving&departure_time=now&traffic_model=best_guess&key={key}&destinations={destinations}
    geocode-url: https://maps.googleapis.com/maps/api/geocode/json

telegram:
  service:
    url: http://localhost:8081/telegram/api/notification
