spring:
  application:
    name: NotifyTrafficIntegration

  datasource:
      url: jdbc:postgresql://localhost:5432/NotifyDB
      username: postgre
      password: postgre
      driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/v1.0.0/db.changelog-master.xml

server:
  port: 8080

google:
  maps:
    token: AIzaSyD7EiwFgtZ3WCcPi6uGRRiVeDqLJQtaejw
    url: https://maps.googleapis.com/maps/api

telegram:
  service:
    url: http://localhost:8081/telegram/api/notification
